import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero'
import Figures from '@/components/Figures'
import Features from '@/components/Features'
import CTA from '@/components/CTA'
import Partnerships from '@/components/Partnerships'
import FeaturesTwo from '@/components/FeaturesTwo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Figures />
        <Features />
        <CTA big text="More Features added as your team grows"/>
        <Partnerships />
        <FeaturesTwo />
        <CTA text="More Features added as your team grows" />
      </main>
    </>
  )
}
